### PR TITLE
Have jenkins fail if the benchmark errors

### LINKED ISSUE #361: jenkins didn't report failed benchmark
benchmark errored https://magic-ci-atp.it.csiro.au/job/entity-service/job/develop/108/execution/node/77/log/ but jenkins gave it the thumbs up anyway.

Is that the desired behavior?

### PR DESCRIPTION
**Pull request by hardbyte**
- Fails if the benchmark container exits incorrectly (due to bad configuration).
- Fails if the benchmark results contain status=ERROR entries.
- Removes the default server address for benchmark container.

Closes #361

### CODE REVIEW

File: Jenkinsfile.groovy [hunk 1]
```diff
@@ -149,11 +149,27 @@ node('docker&&multicore&&ram') {
...
+          sh """
           docker cp ${benchmarkContainerName}:/app/results.json results.json
           """
-
           archiveArtifacts artifacts: "results.json", fingerprint: true
+          // Read the JSON file and fail if there was an ERROR
+          def benchmarkResults = readJSON file: 'results.json'
+          print(benchmarkResults["version"])
+          for (String item : benchmarkResults["experiments"]) {
+               if(item["status"] == "ERROR") {
```
Comment (wilko77) [inline Jenkinsfile.groovy]: I would test for success and otherwise fail. (There might be other statuses like 'running', etc.)
Oh, and add a space after the `if`. 
```if (item["status"] != "completed") {```

Comment (hardbyte) [reply Jenkinsfile.groovy]: fair enough, I'm going to trust you on the `"completed"`
